language: c
compiler:
- clang
- gcc
sudo: required
script: make
env:
  global:
   - secure: FjVL6HME24GSWyUnvZJUQ2c3/tzRMgmR4EF8k9HN6g8m1Io8nKWpOcz31V7GNV3Ve5J6/jk7jYjlfiavpOs+d4yhDV6QNsTKMvyCVWBwx0FrzyRjvN4yORspBBt2fs42VNTSZ7nFmdUbCL7d4b5Zvv2LHjT/DeZxTPLdItfDK08qVbWhn5C+Qz5UOdzMUYEQf+A4cQyGl/Xs8sVu0XCiVCgb+2pMyc75nBupIHu2HKDvl+3sYh85sxvochVraKOb2OB7wzV5TeNxyBSBJoMIWz5LUIgvY2qsPVZjwgdSK4a6opMJMa1Aufpa+SOR4irOGh4Qx4h4cz4I4cxwH8f5QAZuD3XQnn5FOyN4y9cwa83NIO30ZEZ6CG50AuzBo5xxFseVVTnsHr5l3OpPiIr8kSO+S9sAwUzaBYj4QkGU4w6TluLna0uU3tJheQ1DE/krV6HjwyApt2pQppt7Lf9erp+5UcBwWt1tph3LEYuv/61dHlJB/l263znIZfS40Q3nj/EKpWvNtJX1vd5Ya+5Lzo5Fqd909lzs/GUBKrkjmjBu2n74YaHPkPtQMalJvW3UHLEeZeLkXV50wb7j3JKqVzVWp5S2UkFVMBx4NHVpVL57+PJLYLmTWGyGWY5KokcZ/fNtuxQTgSTI/6I4KdQ9T1X8jLA25hN9bbneB2YgN5A=
before_install:
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN
  CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: lovasko/nemo-core
      description: Unicast network monitor
    notification_email: daniel.lovasko@gmail.com
    build_command_prepend: true
    build_command: make
    branch_pattern: master
