# Copyright (c) 2018 Daniel Lovasko.
# All Rights Reserved
#
# Distributed under the terms of the 2-clause BSD License. The full
# license is in the file LICENSE, distributed as part of this software.

language: c
compiler:
 - clang
 - gcc
sudo: required
script: make
